import { readFileSync, writeFileSync, existsSync } from 'fs';
const { dreams } = await import('../data/dreams.js');
const cache = JSON.parse(readFileSync('scripts/dreams-uz-cache.json', 'utf8'));
console.log('Cache entries:', Object.keys(cache).length);
const lines = [
  '// Auto-generated by scripts/translate-dreams-uz-gt.mts',
  '// Do not edit manually — re-run the script to regenerate',
  '',
  'export interface DreamUzTranslation {',
  '  title: string;',
  '  short: string;',
  '  full: string;',
  '  forWoman: string;',
  '  forMan: string;',
  '  byDay: Record<string, string>;',
  '  tags: string[];',
  '}',
  '',
  'export const dreamsUz: Record<string, DreamUzTranslation> = {',
];
const written_slugs = new Set<string>();
let written = 0;
for (const dream of dreams) {
  const uz = cache[dream.slug];
  if (!uz) continue;
  if (written_slugs.has(dream.slug)) continue;
  written_slugs.add(dream.slug);
  lines.push(`  '${dream.slug}': {`);
  lines.push(`    title: ${JSON.stringify(uz.title)},`);
  lines.push(`    short: ${JSON.stringify(uz.short)},`);
  lines.push(`    full: ${JSON.stringify(uz.full)},`);
  lines.push(`    forWoman: ${JSON.stringify(uz.forWoman)},`);
  lines.push(`    forMan: ${JSON.stringify(uz.forMan)},`);
  lines.push(`    byDay: {`);
  for (const [day, text] of Object.entries(uz.byDay as Record<string, string>)) {
    lines.push(`      ${day}: ${JSON.stringify(text)},`);
  }
  lines.push(`    },`);
  lines.push(`    tags: ${JSON.stringify(uz.tags)},`);
  lines.push(`  },`);
  written++;
}
lines.push('};');
writeFileSync('data/dreams-uz.ts', lines.join('\n'));
console.log('Written:', written, 'dreams to data/dreams-uz.ts');
