/**
 * translate-dreams-uz-gt.mts
 * Translates all 503 dreams from Russian to Uzbek using MyMemory API (free, no API key).
 * Run: npx tsx scripts/translate-dreams-uz-gt.mts
 * Output: data/dreams-uz.ts
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';

const { dreams } = await import('../data/dreams.js');

const OUTPUT_FILE = 'data/dreams-uz.ts';
const CACHE_FILE = 'scripts/dreams-uz-cache.json';
const DELAY_MS = 600;        // delay between dreams
const CHUNK_SIZE = 450;      // max chars per MyMemory request
const EMAIL = 'azizbek.saatov@gmail.com';

interface DreamUz {
  title: string;
  short: string;
  full: string;
  forWoman: string;
  forMan: string;
  byDay: Record<string, string>;
  tags: string[];
}

let cache: Record<string, DreamUz> = {};
if (existsSync(CACHE_FILE)) {
  cache = JSON.parse(readFileSync(CACHE_FILE, 'utf8'));
  console.log(`Loaded cache: ${Object.keys(cache).length} dreams already translated`);
}

async function myMemoryTranslate(text: string): Promise<string> {
  if (!text.trim()) return text;
  const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=ru|uz&de=${EMAIL}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json() as { responseStatus: number; responseData: { translatedText: string } };
  if (data.responseStatus !== 200) throw new Error(`API error ${data.responseStatus}`);
  return data.responseData.translatedText;
}

// Split text into chunks of <= CHUNK_SIZE chars, split on sentence boundary if possible
function splitChunks(text: string): string[] {
  if (text.length <= CHUNK_SIZE) return [text];
  const chunks: string[] = [];
  let remaining = text;
  while (remaining.length > CHUNK_SIZE) {
    let cut = CHUNK_SIZE;
    // Try to split on period or space
    const periodPos = remaining.lastIndexOf('. ', CHUNK_SIZE);
    if (periodPos > CHUNK_SIZE / 2) cut = periodPos + 2;
    else {
      const spacePos = remaining.lastIndexOf(' ', CHUNK_SIZE);
      if (spacePos > CHUNK_SIZE / 2) cut = spacePos + 1;
    }
    chunks.push(remaining.slice(0, cut).trim());
    remaining = remaining.slice(cut).trim();
  }
  if (remaining) chunks.push(remaining);
  return chunks;
}

async function tr(text: string): Promise<string> {
  if (!text.trim()) return text;
  const chunks = splitChunks(text);
  if (chunks.length === 1) return myMemoryTranslate(text);
  const parts: string[] = [];
  for (const chunk of chunks) {
    parts.push(await myMemoryTranslate(chunk));
    if (chunks.length > 1) await sleep(200);
  }
  return parts.join(' ');
}

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function translateDream(dream: (typeof dreams)[0]): Promise<DreamUz> {
  const title = await tr(dream.title);
  await sleep(150);
  const short = await tr(dream.short);
  await sleep(150);
  const full = await tr(dream.full);
  await sleep(150);
  const forWoman = await tr(dream.forWoman);
  await sleep(150);
  const forMan = await tr(dream.forMan);
  await sleep(150);

  const byDay: Record<string, string> = {};
  for (const [day, text] of Object.entries(dream.byDay)) {
    byDay[day] = await tr(text);
    await sleep(150);
  }

  const tags: string[] = [];
  for (const tag of dream.tags) {
    tags.push(await tr(tag));
    await sleep(100);
  }

  return { title, short, full, forWoman, forMan, byDay, tags };
}

const seenSlugs = new Set<string>();
const remaining = dreams.filter((d) => {
  if (cache[d.slug] || seenSlugs.has(d.slug)) return false;
  seenSlugs.add(d.slug);
  return true;
});
console.log(`Total: ${dreams.length}, remaining: ${remaining.length}`);

for (let i = 0; i < remaining.length; i++) {
  const dream = remaining[i];
  process.stdout.write(`[${i + 1}/${remaining.length}] ${dream.slug} ... `);

  let attempts = 0;
  while (attempts < 3) {
    try {
      cache[dream.slug] = await translateDream(dream);
      writeFileSync(CACHE_FILE, JSON.stringify(cache, null, 2));
      console.log(`✓ (${Object.keys(cache).length}/${dreams.length})`);
      break;
    } catch (err: any) {
      attempts++;
      console.error(`\n  ✗ attempt ${attempts}: ${err.message?.slice(0, 80)}`);
      if (attempts < 3) await sleep(4000);
    }
  }
  if (attempts === 3) console.error('  Skipping');

  if (i + 1 < remaining.length) await sleep(DELAY_MS);
}

// Generate TypeScript output
console.log(`\nGenerating ${OUTPUT_FILE}...`);

const lines: string[] = [
  '// Auto-generated by scripts/translate-dreams-uz-gt.mts',
  '// Do not edit manually — re-run the script to regenerate',
  '',
  'export interface DreamUzTranslation {',
  '  title: string;',
  '  short: string;',
  '  full: string;',
  '  forWoman: string;',
  '  forMan: string;',
  '  byDay: Record<string, string>;',
  '  tags: string[];',
  '}',
  '',
  'export const dreamsUz: Record<string, DreamUzTranslation> = {',
];

const writtenSlugs = new Set<string>();
let written = 0;
for (const dream of dreams) {
  const uz = cache[dream.slug];
  if (!uz) { continue; }
  if (writtenSlugs.has(dream.slug)) continue;
  writtenSlugs.add(dream.slug);
  lines.push(`  '${dream.slug}': {`);
  lines.push(`    title: ${JSON.stringify(uz.title)},`);
  lines.push(`    short: ${JSON.stringify(uz.short)},`);
  lines.push(`    full: ${JSON.stringify(uz.full)},`);
  lines.push(`    forWoman: ${JSON.stringify(uz.forWoman)},`);
  lines.push(`    forMan: ${JSON.stringify(uz.forMan)},`);
  lines.push(`    byDay: {`);
  for (const [day, text] of Object.entries(uz.byDay)) {
    lines.push(`      ${day}: ${JSON.stringify(text)},`);
  }
  lines.push(`    },`);
  lines.push(`    tags: ${JSON.stringify(uz.tags)},`);
  lines.push(`  },`);
  written++;
}

lines.push('};');
writeFileSync(OUTPUT_FILE, lines.join('\n'));
console.log(`✓ Written ${OUTPUT_FILE} (${written} dreams)`);
